config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration' },
    controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] do
    member do
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch '/update_phone_number' => 'users#update_phone_number'
    end
  end
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'listing'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: %i[create destroy]
    resources :reservations, only: [:create]
    resources :calendars
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'

  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
      post '/approve' => 'reservations#approve'
      post '/decline' => 'reservations#decline'
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get '/host_calendar' => 'calendars#host'
  get '/payment_method' => 'users#payment'
  get '/payout_method' => 'users#payout'
  post '/add_card' => 'users#add_card'

  get '/notification_settings' => 'settings#edit'
  post '/notification_settings' => 'settings#update'

  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:edit, :update]

  def edit
  end

  def update
    if @setting.update(setting_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot save..."
    end
    render 'edit'
  end

  private

  def setting_params
    params.require(:setting).permit(:enable_sms, :enable_email)
  end

  def set_setting
    @setting = User.find(current_user.id).setting
  end
end

app/views/settings/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Payment Method", payment_method_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Payout Method", payout_method_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Notification Settings", notification_settings_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">Notification Settings</div>
      <div class="panel-body">
        <div class="container">
          <%= form_for :setting do |f| %>
            <div class="row form-group">
              <div class="col-md-6 text-center">
                <%= f.check_box :enable_email %> Email
              </div>
              <div class="col-md-6 text-center">
                <%= f.check_box :enable_sms %> SMS
              </div>
            </div>
            <div class="text-center">
              <%= f.submit "Save Your Settings", class: "btn btn-normal" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>